name: OctoBay API - Test, Build, Push, Deploy

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout OctoBay/api
  #       uses: actions/checkout@v2
  #     - name: Use Node.js 16.x
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16.x"
    
  build-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: script
      run: echo $CI
    - name: script
      run: echo $DOCKER_USERNAME
    - name: Build & Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: octobay/api
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}